// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaVFoVbnuVysE6ff48qkp-NzqnbFhik7w',
    appId: '1:319361318329:web:336addaeb3c07a1cebca68',
    messagingSenderId: '319361318329',
    projectId: 'translation-app-782b6',
    authDomain: 'translation-app-782b6.firebaseapp.com',
    storageBucket: 'translation-app-782b6.appspot.com',
    measurementId: 'G-85QF97RC15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdIWEykCbZJ7XWrBbTNV_d0hplsZFzHJk',
    appId: '1:319361318329:android:bfd04592985ae7c1ebca68',
    messagingSenderId: '319361318329',
    projectId: 'translation-app-782b6',
    storageBucket: 'translation-app-782b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClPJRn-QQJodLeXobLYPnRZqgDT6elBBc',
    appId: '1:319361318329:ios:f2b1fb2efcd79000ebca68',
    messagingSenderId: '319361318329',
    projectId: 'translation-app-782b6',
    storageBucket: 'translation-app-782b6.appspot.com',
    iosClientId: '319361318329-8vphpmjm04uqfncjeqgbm8b5asjb3qji.apps.googleusercontent.com',
    iosBundleId: 'com.example.translation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClPJRn-QQJodLeXobLYPnRZqgDT6elBBc',
    appId: '1:319361318329:ios:f2b1fb2efcd79000ebca68',
    messagingSenderId: '319361318329',
    projectId: 'translation-app-782b6',
    storageBucket: 'translation-app-782b6.appspot.com',
    iosClientId: '319361318329-8vphpmjm04uqfncjeqgbm8b5asjb3qji.apps.googleusercontent.com',
    iosBundleId: 'com.example.translation',
  );
}
